/**
 * Next.js 项目脚手架生成
 */

import * as fs from 'fs/promises';
import * as path from 'path';
import * as os from 'os';
import type { PageStructureResult } from '@/types/analyzer';
import type { ScrapeResult } from '@/types/scrape';
import { generateComponent } from './component-generator';
import { getMatchingService, getFallbackCode } from './fallback-templates';

function getComponentName(blockType: string, index: number, seen: Set<string>): string {
  const base: Record<string, string> = {
    navbar: 'Navbar',
    hero: 'Hero',
    features: 'Features',
    pricing: 'Pricing',
    testimonials: 'Testimonials',
    faq: 'Faq',
    cta: 'Cta',
    form: 'Form',
    gallery: 'Gallery',
    map: 'Map',
    footer: 'Footer',
    search: 'Search',
    calendar: 'Calendar',
    video: 'Video',
  };
  const baseName = base[blockType] ?? `Block`;
  if (seen.has(baseName)) {
    return `${baseName}${index}`;
  }
  seen.add(baseName);
  return baseName;
}

export interface BuildResult {
  projectPath: string;
  zipPath: string;
}

export async function buildNextJsProject(
  scrapeResult: ScrapeResult,
  analysisResult: PageStructureResult,
  taskId: string,
  targetLanguage: 'original' | 'zh' | 'en' = 'original'
): Promise<BuildResult> {
  const projectDir = path.join(os.tmpdir(), `ch007ai-clone-${taskId}`);
  await fs.mkdir(projectDir, { recursive: true });

  const componentsDir = path.join(projectDir, 'components');
  const appDir = path.join(projectDir, 'app');
  await fs.mkdir(componentsDir, { recursive: true });
  await fs.mkdir(appDir, { recursive: true });

  const { blocks, colorTheme, fontFamily, detectedServices = [] } = analysisResult;
  const imports: string[] = [];
  const elements: string[] = [];
  const seenNames = new Set<string>();

  for (let i = 0; i < blocks.length; i++) {
    const block = blocks[i];
    const componentName = getComponentName(block.type, i, seenNames);
    const fileName = `${componentName}.tsx`;

    try {
      const matchedService = getMatchingService(block.type, detectedServices);
      const fallbackCode = matchedService
        ? getFallbackCode(matchedService, block.type, colorTheme)
        : null;

      const code =
        fallbackCode ?? (await generateComponent(block, colorTheme, targetLanguage));
      await fs.writeFile(path.join(componentsDir, fileName), code, 'utf-8');
      imports.push(`import ${componentName} from '@/components/${componentName}';`);
      elements.push(`        <${componentName} />`);
    } catch (err) {
      console.warn(`[Generator] Failed to generate ${componentName}, using placeholder:`, err);
      const fallback = `'use client';\n\nexport default function ${componentName}() {\n  return (\n    <section className="py-8 px-4 border-b border-gray-200">\n      <h2 className="text-xl font-semibold">${block.title}</h2>\n      <p className="text-gray-500 mt-1">${block.description}</p>\n    </section>\n  );\n}\n`;
      await fs.writeFile(path.join(componentsDir, fileName), fallback, 'utf-8');
      imports.push(`import ${componentName} from '@/components/${componentName}';`);
      elements.push(`        <${componentName} />`);
    }
  }

  const pageTsx = `import type { Metadata } from 'next';
${imports.join('\n')}

export const metadata: Metadata = {
  title: 'Cloned Site',
  description: 'Generated by CH007',
};

export default function HomePage() {
  return (
    <main className="min-h-screen">
${elements.join('\n')}
    </main>
  );
}
`;

  const layoutTsx = `import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'Cloned Site',
  description: 'Generated by CH007',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="antialiased">{children}</body>
    </html>
  );
}
`;

  const globalsCss = `@import "tailwindcss";

:root {
  --primary: ${colorTheme.primary ?? '#4F7EFF'};
  --background: ${colorTheme.background ?? '#ffffff'};
  --foreground: ${colorTheme.text ?? '#1a1a1a'};
}

body {
  font-family: ${fontFamily}, system-ui, sans-serif;
  background: var(--background);
  color: var(--foreground);
}
`;

  const packageJson = {
    name: 'cloned-site',
    version: '0.1.0',
    private: true,
    scripts: {
      dev: 'next dev',
      build: 'next build',
      start: 'next start',
      lint: 'next lint',
    },
    dependencies: {
      next: '15.0.0',
      react: '^19.0.0',
      'react-dom': '^19.0.0',
    },
    devDependencies: {
      typescript: '^5',
      '@types/node': '^20',
      '@types/react': '^19',
      '@types/react-dom': '^19',
      tailwindcss: '^4',
      postcss: '^8',
    },
  };

  const tailwindConfig = `/** @type {import('tailwindcss').Config} */
export default {};
`;

  const tsconfig = {
    compilerOptions: {
      target: 'es5',
      lib: ['dom', 'dom.iterable', 'esnext'],
      allowJs: true,
      skipLibCheck: true,
      strict: true,
      noEmit: true,
      esModuleInterop: true,
      module: 'esnext',
      moduleResolution: 'bundler',
      resolveJsonModule: true,
      isolatedModules: true,
      jsx: 'preserve',
      incremental: true,
      paths: { '@/*': ['./*'] },
      plugins: [{ name: 'next' }],
    },
    include: ['next-env.d.ts', '**/*.ts', '**/*.tsx'],
    exclude: ['node_modules'],
  };

  const nextConfig = `/** @type {import('next').NextConfig} */
const nextConfig = {};
module.exports = nextConfig;
`;

  const postcssConfig = `export default {
  plugins: {
    '@tailwindcss/postcss': {},
  },
};
`;

  await fs.writeFile(path.join(projectDir, 'postcss.config.mjs'), postcssConfig, 'utf-8');
  await fs.writeFile(path.join(appDir, 'page.tsx'), pageTsx, 'utf-8');
  await fs.writeFile(path.join(appDir, 'layout.tsx'), layoutTsx, 'utf-8');
  await fs.writeFile(path.join(appDir, 'globals.css'), globalsCss, 'utf-8');
  await fs.writeFile(
    path.join(projectDir, 'package.json'),
    JSON.stringify(packageJson, null, 2),
    'utf-8'
  );
  await fs.writeFile(
    path.join(projectDir, 'tailwind.config.mjs'),
    tailwindConfig,
    'utf-8'
  );
  await fs.writeFile(
    path.join(projectDir, 'tsconfig.json'),
    JSON.stringify(tsconfig, null, 2),
    'utf-8'
  );
  await fs.writeFile(
    path.join(projectDir, 'next.config.js'),
    nextConfig,
    'utf-8'
  );

  const zipPath = path.join(os.tmpdir(), `ch007ai-clone-${taskId}.zip`);
  await createZip(projectDir, zipPath);

  return { projectPath: projectDir, zipPath };
}

async function createZip(sourceDir: string, outputPath: string): Promise<void> {
  const archiver = (await import('archiver')).default;
  const output = (await import('fs')).createWriteStream(outputPath);
  const archive = archiver('zip', { zlib: { level: 5 } });

  return new Promise((resolve, reject) => {
    output.on('close', resolve);
    archive.on('error', reject);
    archive.pipe(output);

    archive.directory(sourceDir, 'cloned-site');
    archive.finalize();
  });
}

/** 从项目目录重新生成 zip（修复循环后更新 zip 时使用）*/
export async function updateZipFromProject(
  projectPath: string,
  zipPath: string
): Promise<void> {
  await createZip(projectPath, zipPath);
}
